# Elasticsearch 6.3.1

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/elasticsearch/elasticsearch:6.3.1@sha256:178051b116c91ae525369f3468aec167fb2c1cd90456e86c717cb1d135b8595e

# The upstream image was built by:
#   https://github.com/elastic/elasticsearch-docker/tree/6.3.1

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/elasticsearch/reference/6.3.1/docker.html
