# Elasticsearch 6.3.0

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/elasticsearch/elasticsearch:6.3.0@sha256:3169b4009903c47245d3bf81d8a7b11ab22ce2965598823384e5c4bbd4298316

# The upstream image was built by:
#   https://github.com/elastic/elasticsearch-docker/tree/6.3.0

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/elasticsearch/reference/6.3.0/docker.html
